services:
  - type: web
    name: rl-analyzer
    runtime: python
    repo: https://github.com/rlomar/rl-analyzer
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: rl-analyzer-db
          property: connectionString
databases:
  - name: rl-analyzer-db
    plan: free
    databaseName: rlanalyzer
    ipAllowList: []
